---
title: "Chapter 3 Answers"
geometry: margin=1.0in
---
\pagenumbering{gobble}

# Exercises, Chapter 3

__3.1__ The Economic Order Quantity model, or EOQ model, gives the optimal output order quantity as 

$\displaystyle Q = \sqrt{\frac{2DK}{h}}$

where $D$ is the annual demand, $K$ is the fixed cost per order, and $h$ is the annual holding cost per item. 
The EOQ model is used to solve for _inventory control_ problems and is appropriate when demand for items can be assumed to be constant over time.
Write R commands that set the objects ```D, K,``` and ```h``` to

```D = 1000, K = 5, and h = 0.25```

and compute the associated bvalue of ```Q```.

__3.2__ For an initial principle amount $P$ and a nominal annual interest rate $r$ that is compounded $n$ times per year over a span of $t$ years, the final value of a certificate of deposit is

$F = P(1+\frac{r}{n})^{nt}$

Write R commands that set the objects ```P, r, n,``` and ```t``` to

```P = 100, r = 0.08, n = 12, and t = 3```

and compute the associated value of ```F```


__Exercises taken from indicated chapter of "Learning Base R", by Lawrence M Leemis, ISBN 978-0-9829174-8-0__

