---
title: "Chapter 5 Questions"
geometry: margin=1.0in
---
\pagenumbering{gobble}
# Exercises, Chapter 5

__5.1__ Using the _minimum number of keystrokes,_ write a single R command that constructs the matrix _A_ given below.

\[
    A=
    \left[ {\begin{array}{ccccc}
    5 & 6 & 7 & 8 & 9\\
    12 & 12 & 12 & 12 & 12\\
    81 & 64 & 49 & 36 & 25\\
    2 & 8 & 4 & 7 & 3\\
    \end{array} } \right]
\]

__5.2__ Write R commands that create a 2 x 4 matrix named _x_ that contains the inteegers 11, 12, ..., 18 arranged in a column-wise fashion.
Then use subscripts that extact the elements that exclude the first row and include the first and fourth columns.

__5.3__ Let A and B be the following 3 x 2 matrices:

\[
    A=
    \left[ {\begin{array}{cc}
    1 & 4\\
    2 & 5\\
    3 & 6\\
    \end{array} } \right]
\]

\[
    B=
    \left[ {\begin{array}{cc}
    7 & 10\\
    8 & 11\\
    9 & 12\\
    \end{array} } \right]
\]

Write R commands to create the matrices _A_ and _B_ using the ```matrix``` function, then combine _A_ and _B_ to create two new matrices with the ```rbind``` and ```cbind``` functions.

__5.4__ A _one-step transition matrix_ has elements that are between 0 and 1, row sums that equal 1, and the same number of rows and columns.
Write an R command to create the 2 x 2 one-step transition matrix _A_ with elements given by

\[
    A=
    \left[ {\begin{array}{cc}
    0.8 & 0.2\\
    0.3 & 0.7\\
    \end{array} } \right]
\]

__5.5__ Write a single R command that creates a sequence of one 1, two 2s, three 3s, and four 4s, and places them in a 2 x 5 matrix named ```b``` in a row-wise fashion.
This command should use as few keystrokes as possible.

__Exercises taken from indicated chapter of "Learning Base R", by Lawrence M Leemis, ISBN 978-0-9829174-8-0__

