---
title: "Chapter 7 Questions"
geometry: margin=1.0in
---
\pagenumbering{gobble}


__7.1__ Write a single R command that calculates: $sin(e^4 + \sqrt{arccos(1/3)})$

__7.2__ What is returned by the following R command ? (Guess before computing this in R.)

```
x <- c(pi, 4/3, 7)
round(x,2)
```

__7.3__ What is returned by the following R commands ?

```
x <- (1:10)^2
diff(range(x))
```

__7.4__ What is returned by the following R commands ?

```
x <- 1:4
y <- 4:1
pmax(x,y)
```

__7.5__ What is returned by the following R commands ?

```
x <- 1:4
cumsum(x)
```

__7.6__ What is returned by the following R commands ?

```
x <- c(1,1,1,-1,-1,-1,NA)
y <- c(0,1,4, 0,-1,NA, 1)
x / sqrt(y)
```

__7.7__ What is returned by the following R commands ?

```
x <- seq(1,7,by=3)
sum(x^2) / length(x)
```

__7.8__ What is returned by the following R commands ?

```
sqrt(max(9:-3))
```

__7.9__ Let ```x``` be a vector of length three or greater that contains numeric elements.
Write a single R command that calculates the sample mean of all of the elements of ```x``` except the smallest and largest.

__7.10__ Write an R command that creates a 2 x 3 matrix named ```x``` that contains the first six positive integers entered row-wise into the matrix.
Display ```x```.
Then write another R command that uses the ```dim``` function to change the dimensions of ```x``` to a 3 x 2 matrix.
Display the updated matrix ```x```.

__7.11__ Write two R commands that calculate $\displaystyle \sum_{i=1}^{15}\Big(\frac{2^i}{i!} - \frac{cos(3i)}{i^4}\Big)$

__7.12__ Write two R commands that calculate 

$\displaystyle \prod_{x=4}^{12}\Big\lvert \frac{x(x-1)(x-2)}{(x-3)!} + \frac{arctan(x)}{x^2} \Big\rvert$

__7.13__ Write a single R command that calculates: 

$\frac{3}{4} + 
\Big( \frac{3}{4} \cdot \frac{5}{6}  \Big) +
\Big( \frac{3}{4} \cdot \frac{5}{6}  \cdot \frac{7}{8} \Big)
+ \cdot \cdot \cdot +
\Big( \frac{3}{4} \cdot \frac{5}{6}  \cdot \frac{7}{8} \cdot \cdot \cdot \frac{49}{50} \Big)$

__7.14__ Write a single R command that calculates $e^e$.

__7.15__ Write a single R command that calculates:  $\displaystyle1^3 + 2^3 + \cdot \cdot \cdot + 100^3$

__7.16__ Using a minimum number of keystrokes, write a single R command that creates a vector with elements: 

$\displaystyle \Big( 5, \frac{5^2}{2!}, \frac{5^3}{3!}, \cdot \cdot \cdot, \frac{5^{10}}{10!}\Big)$

__7.17__ Write a single R command that calculates: 

$\displaystyle
\sum_{i=3}^{8}\sum_{j=2}^{9}\frac{i^2}{7+4j}$

Which simplifies to:

$\displaystyle 
\Big(\sum_{i=3}^{8}i^2\Big)\Big(\sum_{j=2}^{9}\frac{1}{7+4j}\Big)$

__7.18__ The two-element vector named ```point1``` contains the _x_-coordinate and the _y_-coordinate of a point on the Cartesian coordinate system.
Likewise for ```point2```.
Write a single R command that calculates the quantity of interest requested below.

1. Calculate the distance between the two points, where "distance" is interpreted as the Euclidean distance, the distance "as the crow flies," or the $L_2$ norm.
1. Calculate the rectilinear distance between the two points, where "rectilinear distance" is interpreted as the "Manhattan distance", "taxicab norm," or the $L_1$ norm.

__7.19__ Experiment with the ```Sys.sleep``` function using a single argument, a small integer, to determine its purpose.

__7.20__ Compose two R functions so as to count the number of distinct elements in a vector named ```x```.

__7.21__ An unsorted 99-element vector named ```x``` contains all but one of the first 100 positive integers.
Write a single R command that determines the missing integer.

__Exercises taken from indicated chapter of "Learning Base R", by Lawrence M Leemis, ISBN 978-0-9829174-8-0__

