---
title: "Chapter 8 Questions"
geometry: margin=1.0in
---
\pagenumbering{gobble}

__8.1__ Write a one-line function named ```reverse``` with a single arument ```x``` that reverses the order of the elements in the vector ```x```.

__8.2__ Write a functions namd ```my.cos``` (that calculates the cosine of the supplied angle) with two arguments.
The first argument is named ```angle``` and the second argument is named ```degrees```, which has a default value of ```FALSE```.
Test your function with the R commands 

```
> my.cos(pi/2)
> my.cos(90, degrees = TRUE)
```

__8.3__  Write a function named ```cube.root``` that calculates the cube root(s) of its argument.
Test your function with the R command
```
> cube.root(c(-8,8,729,1000000))
```

__8.4__ Consider the sample data values $x_1, x_2, \cdot \cdot \cdot, x_n$ and the associated sample order statistics, $x_{(1)}, x_{(2)}, \cdot \cdot \cdot, x_{(n)}$.
The _sample truncated mean_ (also known as the _sample trimmed mean_) is a measure of central tendency defined as 

\begin{center}
$\displaystyle \bar{x} = \frac{x_{(k+1)} + x_{(k+2)} + \cdot \cdot \cdot + x_{(n-k)} }{ n - 2k }$
\end{center}

This is the arithmetic average of the data values with the _k_ lowest and _k_ highest observations removed.
The truncated mean is less sensitive to outliers than the arithmetic mean and is hence known as a _robust estimator_.
This estimator is used in sports that are evaluated by a panel of _n_ judges in which the lowest and highest scores (_k_ = 1) are discarded.
Likewise, the truncated mean is used in calculating the London Interbank Offer Rate (LIBOR) when _n_ = 18 interest rates are collected, and the lowest four and highest four interest rates (_k_ = 4) are discarded.
Assuming that $k < n/2$, write an R function named ```tmean``` with two arguments ```x``` and ```k``` that calculates the sample truncated mean of the elements in the vector ```x``` discarding the ```k``` lowest and ```k``` highest observations.
Test your code with the R commands

```
> tmean(c(9.4, 9.6, 9.1, 9.5, 9.3), 1)
> tmean(1:18, 4)
```

__8.5__ Let $x_1, x_2, \cdot \cdot \cdot, x_n$ be the $n > 2$ elements in a vector ```x```.
Write an R function named ```moveave``` with a single argument ```x``` that returns a vector of length $n-1$ whose elements are the moving averages

\begin{center}
$\displaystyle \frac{x_1 + x_2}{2} ,\frac{x_2 + x_3}{2} ,\frac{x_3 + x_4}{2} ,\cdot \cdot \cdot, \frac{x_{n-1} + x_n}{2}$
\end{center}

__8.6__ Let $x_1, x_2, \cdot \cdot \cdot, x_n$ denote the elements of the vector ```x```.
Write an R function named ```L2``` with a single vector argument ```x``` that calculates the $L_2$ norm

\begin{center}
$\displaystyle \sqrt{x_1^2 + x_2^2 + \cdot \cdot \cdot + x_n^2}$
\end{center}

Test your function with the R commands
```
> L2(c(3,4))
> L2(c(1,1,1))
```

__8.7__ Let $x_1, x_2, \cdot \cdot \cdot, x_n$ denote the elements of the vector ```x```.
Write an R function named ```Lp``` with a vector argument ```x``` and an integer argument ```p``` that calculates the $p-$norm

\begin{center}
$\displaystyle \Big( \sum_{i=1}^{n} \lvert x_i \rvert ^p \Big)^{(1/p)}$
\end{center}

Test your R function with the R commands

```
Lp(c(3,4),2)
Lp(c(1,1,1),3)
```

__8.8__  The built-in R function ```mean``` calculates the sample mean $\bar{x}$. 
Write R functions named ```hmean, gmean,``` and ```qmean``` that calculate the sample harmonic mean, geometric mean, and quadratic mean defined by

\begin{center}
$\displaystyle 
h = \bigg( \frac{1}{n} \sum_{i=1}^{n}\frac{1}{x_i}\bigg)^{-1}, \hspace{0.2in}
g = \bigg( \prod_{i=1}^{n}x_i \bigg)^{1/n}, \hspace{0.2in}
q = \sqrt{\frac{1}{n} \sum_{i=1}^{n} x_i^2 }
$
\end{center}

where $x_1, x_2, \cdot \cdot \cdot, x_n$ are the data values.
Test your functions with a vector of data values of your choice and verify the inequality

\begin{center}
$\displaystyle
min \{ x_1,x_2,\cdot \cdot \cdot,x_n \} \leq h \leq g \leq \bar{x} \leq q \leq max \{ x_1,x_2,\cdot \cdot \cdot,x_n \}
$
\end{center}

__8.9__ Let $x_1, x_2, \cdot \cdot \cdot, x_n$ be the $n$ elements in the R vector ```x```.
Write an R function named ```mad``` (for _mean absolute deviation_) with a single argument ```x``` that calculates

\begin{center}
$\displaystyle
\frac{1}{n} \sum_{i=1}^{n} \lvert x_i - \bar{x} \rvert
$
\end{center}

where $\bar{x}$ is the sample mean.

_note: this problem includes the $\frac{1}{n}$ correction from author's errata_

__8.10__ Write an R function named ```fifth``` with a single vector argument ```x``` that calculates and returns the sample mean of the 5th, 10th, 15th, ... elements of ```x```.
You may assume that ```x``` has at least five elements.

__8.11__ The rectangular coordinate system uses $x$, the signed horizontal distance from the origin, and $y$, the signed vertical distance from the origin, to describe the point $(x, y)$.
The polar coordinate system, on the other hand, uses $r$, the signed distance from the origin, and $\theta$, the signed angle measured counterclockwise from the polar axis, to describe the point $(r, \theta)$.
Assume that $\theta$ is measured in radians.

+   Write an R function named ```polar2rect``` with arguments ```r``` and ```theta``` that returns a two-element vector that contains the rectangular coordinates associated with the point $(r,\theta)$ in the polar coordinate system.
+   Write an R function named ```rect2polar``` with arguments ```x``` and ```y``` that returns a two-element vector that contains the polar coordinates associated with the point $(x,y)$ in the rectangular coordinate system.

__8.12__ Write a one-line function named ```fourth``` that raises its argument to the fourth power.
Then apply the ```formals, body,``` and ```environment``` functions to ```fourth``` in order to isolate the arguments to the function, the R code that comprises the function, and the location of the objects used in the function.

------------------------------
__Exercises taken from Chapter 8, "Learning Base R", by Lawrence M Leemis, ISBN 978-0-9829174-8-0__

