# Exercises, Chapter 9

+ TODO: Look for way to convert bases using base R
+ TODO: Complete the exercises

## Exercise 9.1

```{r}
# setup
targetListOfValues<-c(1:10)
targetListOfValues
# before
cos(targetListOfValues)
# set displayed digits to three
options(digits=3)
cos(targetListOfValues)
# set display width to 40 characters
options(width=40)
cos(targetListOfValues)
# force scientific notation
options(scipen=-1000)
cos(targetListOfValues)
# resist scientific notation
options(scipen=1000)
cos(targetListOfValues)
```

## Exercise 9.2

```{r}
# setup
targetListOfValues<-c(1:10)
options(digits=10)
options(scipen=1000)
options(display=40)
cosValues<-cos(1:10)
cosValues
# round takes two values
#   the vector of values to be rounded
#   signed integer number of decimal places
round(cosValues,2)
round(cosValues,6)
round(cosValues,-2)
round(314.00*cosValues,-2)

```

## Exercise 9.3

### Exercise 9.3.a
```{r}

```

### Exercise 9.3.b
```{r}

```

### Exercise 9.3.c
```{r}

```

## Exercise 9.4
```{r}
# confirming from text
system2("bc",stdout=TRUE,stderr="",input="obase=2;12.75")

# as requested in problem
system2("bc",stdout=TRUE,stderr="",input="obase=2;scale=4;19/8")

# confirming as equivalent value
x<-system2("bc",stdout=TRUE,stderr="",input="obase=2;scale=4;19/8")
system2("bc",stdout=TRUE,stderr="",input=paste("obase=10;ibase=2;",x))

#`higlighting the problem identified in the text
system2("bc",stdout=TRUE,stderr="",input="obase=2;scale=4;2/5")

# confirming as approximate value
x<-system2("bc",stdout=TRUE,stderr="",input="obase=2;scale=4;2/5")
system2("bc",stdout=TRUE,stderr="",input=paste("obase=10;ibase=2;",x))

```

## Exercise 9.5
```{r}
system2("bc",stdout=TRUE,stderr="",input="obase=8;ibase=2;101111100")
system2("bc",stdout=TRUE,stderr="",input="obase=16;ibase=2;101111100")
system2("bc",stdout=TRUE,stderr="",input="obase=10;ibase=2;101111100")
```

## Exercise 9.6
```{r}

```

## Exercise 9.7
```{r}

```

