# Exercises, Chapter 2

## Exercise 2.1

```{r}
100 * ( 1 + (0.05 / 12) )^24
```
## Exercise 2.2

```{r}
5 %% 2
```

## Exercise 2.3

```{r}
3333 %% 222
```

## Exercise 2.4

```{r}
domainValues<-10^(c(1:10))
# avoid scientific notation
options(scipen=1000)
# increase significant digits
options(digits=22)
# applying formula
rangeValues<- ( 1 + 1/domainValues)^domainValues
# force output to a single column of values
options(width=40)
rangeValues
```

# Exercises, Chapter 3

## Exercise 3.1

```{r}
D<-1000
K<-5
h<-0.25
# implementing square root as an exponent: raised to 1/2
Q<-((2*D*K)/h)^(0.5)
Q
ls()
```

## Exercise 3.2

```{r}

P<-100; r<-0.08; n<-12; t<-3
F<-P*(1+r/n)^(n*t)
F
```

# Exercises, Chapter 4

## Exercise 4.1

```{r}
desiredVector<-rep(c(2.7,8,3),2)
desiredVector
```

## Exercise 4.2

```{r}
desiredVector<-seq(0,2,by=.4)
desiredVector
```

## Exercise 4.3

```{r}
primes      <-  c(2,3,5,7,11,13,17,19,23,29)
composites  <-  c(4,6,8,9,10)
primes[composites]
```

## Exercise 4.4

```{r}
seq(3, 28, by=11) %/% 4
```

## Exercise 4.5

```{r}
seq(0, 2, length.out=5)
```

## Exercise 4.6

```{r}
x<-c(2,0,-5,-7)
x
# negative index means show all in x except for index
# here -2.8, which is truncated to -2, 
# therefore, show all of x except for the second element
x[-2.8]
```

## Exercise 4.7

```{r}
rep(0:2,1:3)
3 ^ rep(0:2,1:3)
```

## Exercise 4.8

```{r}
seed <- rep(1:4)
desiredVector <- c(seed,1+seed,2+seed,3+seed)
desiredVector
# also
rep(1:4,4)+c(rep(0,4),rep(1,4),rep(2,4),rep(3,4))
```

## Exercise 4.9

```{r}
0:(4/.05)*.05
```

## Exercise 4.10

```{r}
x <- seq(1:8)
x
x[6:8]
x[c(6:8)]
x[-c(-6:-8)]
```

## Exercise 4.11

```{r}
(1:10)^(1:10)
```


------------------------------
__Exercises taken from Chapters 2, 3, and 4 of "Learning Base R", by Lawrence M Leemis, ISBN 978-0-9829174-8-0__

