# Exercises, Chapter 8

+ TODO: Finish Exercises

## Exercise 8.1

```{r}

reverse = function (x) x[length(x):1]

reverse(1:15)

x<-sample(100,10,replace=FALSE)
x
reverse(x)
```

## Exercise 8.2

```{r}
my.cos = function(angle=NaN, degrees=FALSE) {
    ifelse(is.na(angle),
            NaN,
            ifelse(degrees,
                    cos(angle),
                    cos(180/pi*angle)
            )
    )
}

my.cos(90,TRUE)
my.cos(90,degrees<-TRUE)
my.cos(pi/2)
my.cos()

```

## Exercise 8.3

```{r}
-8^(1/3)
# but
cube.root <- function(x) { (x)^(1/3) }
cube.root(c(-8,8,729,1000000))
# and
cube.root <- function(x) { as.numeric(x)^(1/3) }
cube.root(c(-8,8,729,1000000))
# so, ...
cube.root <- function(x) { y<-abs(x)^(1/3) ; ifelse(x>=0,y,-y) ; }
cube.root(c(-8,8,729,1000000))
```

## Exercise 8.4

```{r}
tmean = function (x,k) { 
    sorted_x<-sort(x)
    n_from<-k+1
    n_to<-length(x)-k
    mean(sorted_x[n_from:n_to])
}

# case 1
tmean(c(9.4,9.6,9.1,9.5,9.3),1)
# check against :
mean(c(9.4,9.5,9.3))
# case 2
tmean(1:18,4)
# check against :
mean(5:14)
# setup for alternative forms
x<-sample(100,30,replace=FALSE)
x
tmean(x,3)
tmean(x,7)
# alternative form #1
# GOTCHA: parenthesis are REQUIRED on the indexes
tmean = function (x,k) { 
    y<-sort(x)
    mean(y[(k+1):(length(y)-k)])
}

tmean(c(9.4,9.6,9.1,9.5,9.3),1)
tmean(x,3)
tmean(x,7)

# alternative form #2
# sort, then subset, then take the mean
tmean = function (x,k) { mean(sort(x)[(k+1):(length(x)-k)]); }
tmean(c(9.4,9.6,9.1,9.5,9.3),1)
tmean(x,3)
tmean(x,7)
```

## Exercise 8.5
```{r}
moveave = function (x) { (x[1:length(x)-1] + x[2:length(x)])/2 }
moveave(c(1,2,3))
moveave(c(10,20,30,40,50))
```

## Exercise 8.6
```{r}
L2 = function (x) { sqrt(sum(x^2)) }
L2(c(3,4))
L2(c(1,1,1))
sqrt(3)
```

## Exercise 8.7
```{r}
Lp = function (x, p) { (sum(abs(x)^p))^(1/p)}
Lp(c(3,4),2)
Lp(c(1,1,1),3)
3^(1/3)
Lp(c(1,1,1),2)
```

## Exercise 8.8
```{r}
hmean_orig = function (x) { 1/((1/length(x))*(sum(1/x))) }
hmean_simp = function (x) { length(x) / (sum(1/x)) }
gmean      = function (x) { prod(x)^(1/(length(x))) }
qmean_orig = function (x) { sqrt( (1/length(x)) * (sum(x^2)) ) }
qmean_simp = function (x) { sqrt( (sum(x^2))/length(x) ) }

rv <- sample(100,30,replace = FALSE)
rvmin <-min(rv)
h<-hmean_orig(rv)
g<-gmean(rv)
m<-mean(rv)
q<-qmean_orig(rv)
rvmax<-max(rv)

(rvmin <= h) && (h <= g) && (g<=m) && (m<=q) && (q <= rvmax)
```

### Alternate Ending
```{r}
hmean_alt = function (x,n=length(x)) { n / (sum(1/x)) }
gmean_alt = function (x,n=length(x)) { prod(x)^(1/(n)) }
qmean_alt = function (x,n=length(x)) { sqrt( (sum(x^2))/n ) }

h_alt<-hmean_alt(rv)
g_alt<-gmean_alt(rv)
q_alt<-qmean_alt(rv)

(rvmin <= h_alt) && (h_alt <= g_alt) && (g_alt<=m) && (m<=q_alt) && (q_alt <= rvmax)
```

### Summary
```{r}
# using signif() because digits=4 parameter was ignored
library(knitr)
kable(matrix(
    c(
        c('rvmin',rvmin,rvmin),
        c('h',signif(h),signif(h_alt)),
        c('g',signif(g),signif(g_alt)),
        c('m',signif(m),signif(m)),
        c('q',signif(q),signif(q_alt)),
        c('rvmax',rvmax,rvmax)
    ),
    c(6,3),byrow=TRUE),
    col.names=c('variable','Original','Alternate'),
    align=c('r','l','l'),
    caption="A Comparison of Results")
```

## Exercise 8.9
```{r}
mad = function (x,x_bar = mean(x),n = length(x) ) { 
    (sum(abs(x-x_bar)))/n 
    }
mad(c(1,2,3))
mad(c(10,20,30,40,50))

```
